
sunrisemasaladetail=" Made from select ingredients. Sunrise Pure has been trusted for preparing traditional recipes in home, Providing consistency in taste and its uncompromising standard of quality. With 100 years of expertise. It is Only excellence that We wish to offer."
const products = [
          
    //--------------SNACKS-Cheaps------ 

    {
        id: 11001,
        name: "KurKure",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "new arrival",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "chips",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
    },
    {
    id: 11002,
    name: "tedhe medhe",
    price: 5,
    originalPrice: 5,
    delivery_time: "20 min",
    message: "",
    amount: "",
    thumbnail1: "",
    thumbnail2: "",
    thumbnail3: "",
    category: "snacks",
    sub_category: "chips",
    image: "",
    little_details: "",
    details: "",
    quantity: 1
    },
    
    {
        id: 11003,
        name: " red Lays",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "chips",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
    },
    {
        id: 11004,
        name: " green Lays",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "chips",
        image: "",
        little_details: "",
        details: "very tasty",
        quantity: 1
    },



//--------------SNACKS-Noodles------ 
    {
        id: 12001,
        name: "Maggi",
        price: 7,
        originalPrice: 7,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "noodle",
        image: "product images/Snack/maggi.png",
        little_details: "2 Minutes ",
        details: "Ready in 2 minutes",
        quantity: 1
    },
    {
        id: 12002,
        name: "Yippe!",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "noodle",
        image: "product images/Snack/yipee.webp",
        little_details: "2 Minutes ",
        details: "",
        quantity: 1
    },
    {
        id: 12003,
        name: "Richik chow",
        price: 30,
        originalPrice: 40,
        delivery_time: "20 min",
       amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "noodle",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
    },
    {
        id: 12004,
        name: "Royal chow",
        price: 28,
        originalPrice: 40,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "noodle",
        image: "product images/snack/royal chow.JPG",
        little_details: "",
        details: "",
        quantity: 1
    },
    {
        id: 12005,
        name: "Amrita chow",
        price: 20,
        originalPrice: 35,
        delivery_time: "20 min",
        message: "",
        amount: " ",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "noodle",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
    },
    {
        id: 12006,
        name: "Jamuna long chow",
        price: '',
        originalPrice: 0,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "noodle",
        image: "product images/snack/jamuna chow.JPG",
        little_details: "chinese style",
        details: "",
        quantity: 1
    },
    
// ----------------Snacks-Chira------------

    {
        id: 13001,
        name: "nasta 24 ghanta",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "chira",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
    },

// ----------------Snacks-Cakes------------

    {
    id: 11010,
        name: "desire Chocolate Cake",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "16.80g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "snacks",
        sub_category: "cake",
        image: "product images/snack/desire chocolate cake.JPG",
        little_details: "Chocolate cake filled with chocolate cream - Desire",
        details: "",
        quantity: 1
},






//-----------Best-Deal--------
{
    id: 21001,
    name: "sprite 750ml",
    price: 35,
    originalPrice: 40,
    delivery_time: "20 min",
    message: "new arrival",
    // Set the expiration date and time for the offer
    timer: "2025-10-16T08:39:59", 
    amount: "750ml",
    thumbnail1: "",
    thumbnail2: "",
    thumbnail3: "",
    category: "bestdeal", // This product will have a timer
    sub_category: "cold drink",
    image: "product images/cold drink/sprite 750.JPG",
    little_details: "super cold",
    details: "",
    quantity: 1
},
{
    id: 21002,
        name: "amulspray",
        price: 45,
        originalPrice: 48,
        delivery_time: "20 min",
        message: "",
        timer: "2025-10-15T10:06:59", 
        amount: "100g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "bestdeal",
        sub_category: "milk powder",
        image: "product images/other/milk powder amul 100.JPG",
        little_details: "Infant milk food | Infant milk substitute",
        details: " The prepared feed should be used within Half an hour. Otherwise microbial deterioration of the product may set in. Make a fresh preparation for every feed. Discard leftover feed. | Amulspary comes from the house of Amul: The Taste of India ",
        quantity: 1
},
{
    id: 21003,
        name: "soyabean sauce",
        price: 18,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "Recommended",
        timer: "2025-10-14T22:47:35", 
        amount: "jjgx",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "bestdeal",
        sub_category: "sauce",
        image: "product images/daily products/soyabean sauce.png",
        little_details: "value for money",
        details: "Ingredients: Soya beans,Water,Sea Salt,Mirin,Sweet Rice,Cultured Rice,Acidity Regular-260, Preservative-211",
        quantity: 1
},

















//---------------Diterjent powder---------------

{
    id: 71001,
        name: "surf excel",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "75g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "detergent power",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 71002,
        name: "sunlight",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "90g + 10g free",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "detergent power",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 71005,
        name: "sunlight",
        price: 50,
        originalPrice: 50,
        delivery_time: "20 min",
        message: "",
        amount: "500g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "detergent power",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 71003,
        name: "comfort lily fresh",
        price: 4,
        originalPrice: 4,
        delivery_time: "20 min",
        message: "",
        amount: "18ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "fragrance wash",
        image: "product images/detergent/comfortPink.jpg",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 71004,
        name: "comfort morning fresh",
        price: 4,
        originalPrice: 4,
        delivery_time: "20 min",
        message: "",
        amount: "18ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "fragrance wash",
        image: "product images/detergent/comfortBlue.jpg",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 71006,
        name: "active wheel",
        price: 30,
        originalPrice: 30,
        delivery_time: "20 min",
        message: "",
        amount: "400g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "detergent power",
        image: "product images/detergent/wheel.png",
        little_details: "",
        details: "",
        quantity: 1
},









// ----------------------Soap----------
{
    id: 72001,
        name: "chakuliya hindusthan",
        price: 20,
        originalPrice: 24,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 72002,
        name: "ezee godrej",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "36g (34ml)",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 72003,
        name: "vim ",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "60g + 10g free",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/vim soap.JPG",
        little_details: "power of 100 lemons",
        details: "",
        quantity: 1
},
{
    id: 72004,
        name: "godrej no.1 sandal turmeric soap",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "43g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/godrejno1.png",
        little_details: "since 1922 made from 100% vegetable oils",
        details: "",
        quantity: 1
},
{
    id: 72005,
        name: "dove cream bar",
        price: 25,
        originalPrice: 25,
        delivery_time: "20 min",
        message: "",
        amount: "50g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/dove cream bar.png",
        little_details: "beauty bathing cream bar",
        details: "Dove beauty bahing bar cares for your skin giving 24hr nourishment. Its formula is different, it does not dry your skin like ordinary soap | 1/4 moisturising cream | has plant-based cleansers^ | pH balanced formula",
        quantity: 1
},
{
    id: 72006,
        name: "dettol original soap",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "45g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/dettol.png",
        little_details: "protection 99.99% illness causing germs^",
        details: "IMA recommended soap ",
        quantity: 1
},
{
    id: 72007,
        name: "margo neem leavs",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "43g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/margo.png",
        little_details: "vitamin e | moisturisers",
        details: "Margo skin, Clear Skin | ^100% Neem oil Extracted from the original neem Is used in this toilet soap.",
        quantity: 1
},
{
    id: 72008,
        name: "vivel aloe vera + vitamin E",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "44g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 72009,
        name: "lifebouy Expert defence",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "44g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "",
        little_details: "100% stronger skin protection",
        details: "Tested for dermatological saftey and found safe to human skin.",
        quantity: 1
},
{
    id: 72010,
        name: "vivel lime + aloe vera",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "47g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "",
        little_details: "soft fresh skin",
        details: "",
        quantity: 1
},
{
    id: 72011,
        name: "vivel pure neem oil + aloe vera",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "43g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 72012,
        name: "cinthol germ protection",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "40g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/cinthol black.jpg",
        little_details: "intense deo frangrance",
        details: "99.9% Germ protection",
        quantity: 1
},
{
    id: 72013,
        name: "lux Ultimate Glow +",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "43g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/lux.png",
        little_details: "jasmine vitamine c+E",
        details: "",
        quantity: 1
},
{
    id: 72014,
        name: "savlon",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "42g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/savlon.png",
        little_details: "glycerin soft skin",
        details: "Protects from 99.9% germs | Bathing bar",
        quantity: 1
},
{
    id: 72015,
        name: "lifebouy lemon aloe fresh",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "44g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "",
        little_details: "12 hour deo fresh",
        details: "",
        quantity: 1
},
{
    id: 72016,
        name: "Bati soap",
        price: 24,
        originalPrice: 24,
        delivery_time: "20 min",
        message: "",
        amount: "44g",
        thumbnail1: "",
        thumbnail2: "product images/soap/battsoap.jpg",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "soap",
        image: "product images/soap/baatsoap.jpg",
        little_details: "12 hour deo fresh",
        details: "",
        quantity: 1
},













// -------------------shampoo-------------
{
    id: 73001,
        name: "silk-n shine",
        price: 4,
        originalPrice: 4,
        delivery_time: "20 min",
        message: "",
        amount: "2ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "shampoo",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 73002,
        name: "sunsilk thick & long",
        price: 1,
        originalPrice: 1,
        delivery_time: "20 min",
        message: "",
        amount: "5.5ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "shampoo",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 73003,
        name: "sunsilk black shine",
        price: 1,
        originalPrice: 1,
        delivery_time: "20 min",
        message: "",
        amount: "6ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "shampoo",
        image: "product images/sampoo/sunshilkBlack.jpg",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 73004,
        name: "clinic plus+ egg protein",
        price: 1,
        originalPrice: 1,
        delivery_time: "20 min",
        message: "",
        amount: "6ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "shampoo",
        image: "product images/sampoo/clinicplusEgg.jpg",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 73005,
        name: "clinic plus+ milk protein ",
        price: 1,
        originalPrice: 1,
        delivery_time: "20 min",
        message: "",
        amount: "6ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "shampoo",
        image: "product images/sampoo/clinicPlusMilk.jpg",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 73006,
        name: "dove hair rescue shampoo",
        price: 2,
        originalPrice: 2,
        delivery_time: "20 min",
        message: "",
        amount: "6ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "shampoo",
        image: "product images/sampoo/doveSampoo.png",
        little_details: "",
        details: "",
        quantity: 1
},



//---------------conditioner----------------
{
    id: 74001,
        name: "dove hair fall rescue conditioner",
        price: 4,
        originalPrice: 4,
        delivery_time: "20 min",
        message: "",
        amount: "6ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "soapSampooDiterjent",
        sub_category: "conditioner",
        image: "product images/sampoo/doveConditioner.jpg",
        little_details: "",
        details: "",
        quantity: 1
},


















// -----------Oil-hair oil------------------
{
    id: 81001,
        name: "nihar coconut oil uttam",
        price: 73,
        originalPrice: 73,
        delivery_time: "20 min",
        message: "",
        amount: "90ml (80.4g)+25ml (22.3g)",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "hair oil",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 81002,
        name: "anmol gold coconut oil dabour",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "25ml+10ml free (32.03g)",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "hair oil",
        image: "product images/oil/anmol gold coconut oil dabour.png",
        little_details: "100% pure coconut oil",
        details: " ",
        quantity: 1
},

{
    id: 81003,
        name: "nihar coconut oil naturals",
        price: 20,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "",
        amount: "40ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "hair oil",
        image: "product images/oil/nihar coconut oil naturals.png",
        little_details: "nihar naturals coconut hair oil with jasmine & methi seed extract",
        details: "Ingredients: Mineral oil(81% v/v), Coconut oil(18%v/v), Fragrance,BHT,Jasmine Extract, Vitamin E acetate, Methi extract | Type 3 Hair oil.",
        quantity: 1
},









// -------------Oil body oil---------

{
    id: 82001,
        name: "body oil jac olivol",
        price: 58,
        originalPrice: 72,
        delivery_time: "20 min",
        message: "",
        amount: "100ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "body oil",
        image: "product images/oil/body oil jac olivol100ml.png",
        little_details: "For soft,Smooth,Glowing & Healthy Skin",
        details: "With Italian Olive Oil | Ayurvedic proprietary medicine",
        quantity: 1
},
{
    id: 82002,
        name: "body oil jac olivol",
        price: 99,
        originalPrice: 126,
        delivery_time: "20 min",
        message: "",
        amount: "200ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "body oil",
        image: "product images/oil/body oil jac olivol200ml.png",
        little_details: "For soft,Smooth,Glowing & Healthy Skin",
        details: "With Italian Olive Oil | Ayurvedic proprietary medicine",
        quantity: 1
},




// -------------Oil food oil---------

{
    id: 83001,
        name: "refined soyabean oil best choice",
        price: 115,
        originalPrice: 146,
        delivery_time: "20 min",
        message: "",
        amount: "750g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "food oil",
        image: "product images/oil/refinedOil1lfront.jpg",
        little_details: "Made from imported soyabean oil | Free from argemone oil",
        details: "Ingredients: Refined soyabean oil & permitted antioxidants (INS 319 & INS 330), Vitamin A,E & D ",
        quantity: 1
},
{
    id: 83002,
        name: "refined soyabean oil best choice",
        price: 58,
        originalPrice: 75,
        delivery_time: "20 min",
        message: "",
        amount: "375g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "food oil",
        image: "product images/oil/refinedOil500front.jpg",
        little_details: "Made from imported soyabean oil | Free from argemone oil",
        details: "Ingredients: Refined soyabean oil & permitted antioxidants (INS 319 & INS 330), Vitamin A,E & D ",
        quantity: 1
},
{
    id: 83003,
        name: "saloni mustard oil",
        price: 92,
        originalPrice: 116,
        delivery_time: "20 min",
        message: "",
        amount: "500ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "food oil",
        image: "product images/oil/mustardOil500front.png",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 83004,
        name: "saloni mustard oil",
        price: 165,
        originalPrice: 200,
        delivery_time: "20 min",
        message: "",
        amount: "1000ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "oil",
        sub_category: "food oil",
        image: "product images/oil/mustardOil1lfront.png",
        little_details: "",
        details: "",
        quantity: 1
},














//------------------Biscuit-5-rupee--------

{
    id: 91001,
        name: "Good day biscuit",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "Butter Cookies",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "little packs",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 91002,
        name: "jeera wonder biscuit",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "little packs",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 91003,
        name: "blacko biscuit",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "little packs",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 91004,
        name: "strabery biscuit",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "little packs",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 91005,
        name: "happy happy biscuit parle",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "27g + 4.5g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "little packs",
        image: "product images/biscuits/happy happy.JPG",
        little_details: "choco-Chip cookies",
        details: "",
        quantity: 1
},
{
    id: 91006,
        name: "orange biscuit",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "little packs",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},










// ----------biscuit-big-packs---------------------------

{
    id: 92001,
        name: "Raja Golden marie",
        price: 35,
        originalPrice: 35,
        delivery_time: "20 min",
        message: "",
        amount: "220gm +20gm extra",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "product images/biscuits/golden marie.JPG",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 92002,
        name: "vita maie gold britannia",
        price: 45,
        originalPrice: 45,
        delivery_time: "20 min",
        message: "",
        amount: "248gm",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 92003,
        name: "doodh marie nobel",
        price: 30,
        originalPrice: 30,
        delivery_time: "20 min",
        message: "",
        amount: "200g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "product images/biscuits/doodh marie.JPG",
        little_details: "healthier crunchier",
        details: "",
        quantity: 1
},
{
    id: 92004,
        name: "2 in 1 anmol biscuit",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "50.4g + 25% extra",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "product images/biscuits/anmol 2 in 1.JPG",
        little_details: "little sweet little salty",
        details: "Allergen Declaration: Contains Wheat, Milk & Sulphite.",
        quantity: 1
},
{
    id: 92005,
        name: "cream cracker raja",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "70g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "product images/biscuits/raja cream cracker.JPG",
        little_details: "",
        details: " This biscuit contains wheat milk sulphite & Soya hypersensitive Ingredients.",
        quantity: 1
},
{
    id: 92006,
        name: "nutri choice britannia",
        price: 50,
        originalPrice: 50,
        delivery_time: "20 min",
        message: "",
        amount: "295g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "",
        little_details: "sugar free cracker honestly good biscuit",
        details: "It eat sugar free, Zero trans fat, No added colours, Crispy Bite, Signature cream, Cracker taste, Melt in mouth experience with every bite.",
        quantity: 1
},
{
    id: 92007,
        name: "the top bisk farm ",
        price: 30,
        originalPrice: 30,
        delivery_time: "20 min",
        message: "",
        amount: "200g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "product images/biscuits/the top.JPG",
        little_details: "the crisp crunch butter munch",
        details: "",
        quantity: 1
},
{
    id: 92008,
        name: "parle rusk",
        price: 35,
        originalPrice: 35,
        delivery_time: "20 min",
        message: "",
        amount: "182g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "product images/biscuits/parle rusk.JPG",
        little_details: "real elaichi | premium rusk",
        details: " Made from premium ingredients, Parle Rusk is crispy, Delicious and once you try it, Your tea-time Would be incomplete without it.",
        quantity: 1
},
{
    id: 92009,
        name: "jadoo Anmol ",
        price: 30,
        originalPrice: 30,
        delivery_time: "20 min",
        message: "",
        amount: "150g + 32g = 182g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "product images/biscuits/jadoo.JPG",
        little_details: "spicy Masaledaar twist",
        details: "2 Fresh packs inside",
        quantity: 1
},
{
    id: 92010,
        name: "britannia 50 50 classic",
        price: 40,
        originalPrice: 40,
        delivery_time: "20 min",
        message: "",
        amount: "200g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "biscuit",
        sub_category: "big packs",
        image: "",
        little_details: "sweet and salty",
        details: "Contains wheat and sulphite | Energy 63 kcal per 13g serve (approx. 4 biscuits) | 0% Trans fat",
        quantity: 1
},









//------------Cold-Drink--------------
//------sprite----
{
    id: 101001,
        name: "sprite 750ml",
        price: 40,
        originalPrice: 40,
        delivery_time: "20 min",
        message: "", 
        amount: "750ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "colddrink",
        sub_category: "cold drink",
        image: "product images/cold drink/sprite 750.JPG",
        little_details: "",
        details: "",
        quantity: 1
},

{
    id: 101002,
        name: "sprite 2L",
        price: 99,
        originalPrice: 99,
        delivery_time: "20 min",
        message: "",
        amount: "2L",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "colddrink",
        sub_category: "cold drink",
        image: "product images/cold drink/sprite 2L.JPG",
        little_details: "",
        details: "",
        quantity: 1
},

//------thumps up-------
{
    id: 102001,
        name: "thumps up 750ml",
        price: 40,
        originalPrice: 40,
        delivery_time: "20 min",
        message: "",
        amount: "750ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "colddrink",
        sub_category: "cold drink",
        image: "product images/cold drink/thumps up 750.JPG",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 102002,
        name: "thumps up 2L",
        price: 99,
        originalPrice: 99,
        delivery_time: "20 min",
        message: "",
        amount: "2L",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "colddrink",
        sub_category: "cold drink",
        image: "product images/cold drink/thumps up 2l.JPG",
        little_details: "",
        details: "",
        quantity: 1
},
//-----frooti------
{
    id: 103001,
        name: "frooti 600ml",
        price: 40,
        originalPrice: 40,
        delivery_time: "20 min",
        message: "",
        amount: "600ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "colddrink",
        sub_category: "cold drink",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 103002,
        name: "frooti little pack",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "colddrink",
        sub_category: "cold drink",
        image: "product images/cold drink/frooti.png",
        little_details: "",
        details: "",
        quantity: 1
},











//------------------Daily-Use-Produts----------------

// --------------Tea--------------
{
    id: 111001,
        name: "tata Gold tea",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "19g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "tea",
        image: "product images/daily products/tata gold tea.JPG",
        little_details: "rich taste irresistible arroma",
        details: "15% Long Leaves | Gently Rolled",
        quantity: 1
},
{
    id: 111002,
        name: "meri chai ",
        price: 20,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "",
        amount: "75g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "tea",
        image: "",
        little_details: "popular strong CTC tea",
        details: "Specially packed for flavour & freshness",
        quantity: 1
},
// -------------Sauce------------------
{
    id: 112001,
        name: "kissan fresh tomato ketchup",
        price: 15,
        originalPrice: 15,
        delivery_time: "20 min",
        message: "",
        amount: "90g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "sauce",
        image: "product images/daily products/kissan ketchup.JPG",
        little_details: "mostly loved by all",
        details: "Number of serves per pack - Min 5, Per Serve: 15g (1 Tbsp)",
        quantity: 1
},
{
    id: 112002,
        name: "soyabean sauce",
        price: 20,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "Recommended",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "sauce",
        image: "product images/daily products/soyabean sauce.png",
        little_details: "value for money",
        details: "Ingredients: Soya beans,Water,Sea Salt,Mirin,Sweet Rice,Cultured Rice,Acidity Regular-260,Preservative-211",
        quantity: 1
},
// --------------Sattu-------------
{
    id: 113001,
        name: "chana sattu ganesh (ছোলার ছাতু)",
        price: 74,
        originalPrice: 89,
        delivery_time: "20 min",
        message: "",
        amount: "500g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "sattu",
        image: "",
        little_details: "80% of daily protein intake",
        details: "Ganesh since 1936 | 100% Natural | Glutan Free | Preservatives & Chemical free | Mix 100gm Sattu in a glass of water or milk, Stir it well with sugar in water or milk, Your chilled sattu drink is ready in a minute. Ingredients: Roasted gram flour, No preservatives or additives used.",
        quantity: 1
},
//------------Honey----------------
{
    id: 114001,
        name: "honey dabour",
        price: 24,
        originalPrice: 24,
        delivery_time: "20 min",
        message: "",
        amount: "20g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "honey",
        image: "",
        little_details: "world's NO.1 honey",
        details: "100% pure guaranteed by Dabur.",
        quantity: 1
},
//-----------------semai------------
{
    id: 115001,
        name: "semai top",
        price: 20,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "",
        amount: "200g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "semai",
        image: "",
        little_details: "payas & pulav both tasty",
        details: "",
        quantity: 1
},
{
    id: 115002,
        name: "semai vermicelli",
        price: 20,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "",
        amount: "200g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "semai",
        image: "product images/daily products/vermicelli semai.JPG",
        little_details: "payas, pulav, kheer",
        details: "Rich in protein",
        quantity: 1
},
// ---------------Soji------------
{
    id: 116001,
        name: "sooji hindusthan",
        price: 12,
        originalPrice: 12,
        delivery_time: "20 min",
        message: "",
        amount: "200g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "soji",
        image: "product images/daily products/hindusthan sooji.JPG",
        little_details: "use for dosa, puchka, upma, halwa",
        details: " No black particles | No dust particles | No preservatives additives used | Extra Danedar | Scientific process | Ingredients: Whole wheat | Specially made for Upma, Puchka, Rava idli, Rava dosa, and Halwa.",
        quantity: 1
},
// ------------Papad-----------
{
    id: 117001,
        name: "kohinoor bada papad",
        price: 32,
        originalPrice: 35,
        delivery_time: "20 min",
        message: "out of stock",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "papad",
        image: "",
        little_details: "bada papad",
        details: "",
        quantity: 1
},
{
    id: 117002,
        name: "Chota sized papad Anbhu appalam",
        price: 30,
        originalPrice: 35,
        delivery_time: "20 min",
        message: "",
        amount: "75g ",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "papad",
        image: "",
        little_details: "chota papad",
        details: "",
        quantity: 1
},
//------------Atta------------
{
    id: 118001,
        name: "Aashirvaad atta",
        price: 49,
        originalPrice: 50,
        delivery_time: "20 min",
        message: "",
        amount: "1kg",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "atta",
        image: "",
        little_details: "0% maida 100% atta",
        details: "",
        quantity: 1
},
//---------Toothpaste---------
{
    id: 119001,
        name: "dabur red toothpaste",
        price: 20,
        originalPrice: 27,
        delivery_time: "20 min",
        message: "",
        amount: "36g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "toothpaste",
        image: "product images/daily products/dabur red toothpaste.png",
        little_details: "10 clinically proven benefits",
        details: "Direction for use 2-3g twice daily or as directed by a Dentist | POTENT AYURVEDIC INGREDIENTS: Pudina Satva (Peppermint), Laung ka Tall (Syzyglum aromaticum), Shunti (Zingiber officinale), Tomar Beej (Zanthaxylum armatum), Karpura (Cinnamomum camphora), Gairic Powder",
        quantity: 1
},

{
    id: 119002,
        name: "colgate strong teeth toothpaste ",
        price: 20,
        originalPrice: 26,
        delivery_time: "20 min",
        message: "",
        amount: "36g ",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "toothpaste",
        image: "",
        little_details: "calcium boost+ with arginine",
        details: "Direction for use: Brush thoroughly, at least twice a day, or as directed by a dentist or physican • Children under 6 years of age should have adult supervision and use only a pea sized amount • Do not swallow.",
        quantity: 1
},
{
    id: 119003,
        name: "colgate cibaca toothpaste ",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "40g ",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "toothpaste",
        image: "",
        little_details: "anticavity toothpaste",
        details: "Ingredients: Calcium carbonate,Sorbitol,Water,Silica,Sodium lauryl sulphate, Flavor,Cl No:42090,Cellulose gum,Sodium Monofluorophosphate,Sodium Bicarbonate,Sodium silicate,Sodium Saccharin,Benzyl alcohol,Potassium nitrate,Eugenol,Limonene.",
        quantity: 1
},
{
    id: 119004,
        name: "dabur babool toothpaste",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "20g + 20g extra",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "toothpaste",
        image: "",
        little_details: "non-Fluoridated toothpaste",
        details: "NATURALLY STRONG TEETH | HELPS FIGHT CAVITY | TIGHTENS GUMS | FRESH BREATH | Ingredients: Calcium carbonate,Sorbitol,Water,Silica,Sodium lauryl sulphate, Flavor containing Clove & mint oil,Cl No:77891,Babul(Acacia arabica)extract,Cellulose gum,Xanthan gum,Sodium silicate,Sodium Saccharin,Benzyl alcohol,Foaming,Non-Fluoridated Toothpaste",
        quantity: 1
},
{
    id: 119005,
        name: "closeup toothpaste ",
        price: 20,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "",
        amount: "40g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "toothpaste",
        image: "product images/daily products/closeup20.JPG",
        little_details: "25% more value | 18 hours fresh breath",
        details: " Usage Direction: For children under the age of six use a use a pea sized amount under adult supervision, Brush at least twice a day. Visit your dentist regularly. Do not swallow.",
        quantity: 1
},

{
    id: 119006,
        name: "dabur lal powder toothpaste",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "16g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "toothpaste",
        image: "",
        little_details: "healthy gums strong teeth",
        details: "",
        quantity: 1
},
{
    id: 119007,
        name: "Colgate active salt toothpaste",
        price: 20,
        originalPrice: 20,
        delivery_time: "20 min",
        message: "New",
        amount: "34g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "toothpaste",
        image: "",
        little_details: "Fights 99.9% germs",
        details: "Sensitivity | Gum Problems | Cavity",
        quantity: 1
},


//-----------------Incense(dhup)------------------
{
    id: 1110001,
        name: "rakhi bandhan dhup",
        price: "",
        originalPrice: "",
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "incense (dhup)",
        image: "",
        little_details: "niva",
        details: "",
        quantity: 1
},
{
    id: 1110002,
        name: "rajnigandha dhup",
        price: "",
        originalPrice: "",
        delivery_time: "20 min",
        message: "",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "incense (dhup)",
        image: "",
        little_details: "niva",
        details: "",
        quantity: 1
},
{
    id: 1110003,
        name: "avida dhup",
        price: "",
        originalPrice: "",
        delivery_time: "20 min",
        message: "",
        amount: "shalimar legacy of fragrance scince 1976",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "incense (dhup)",
        image: "",
        little_details: "3 in 1  free match box",
        details: "",
        quantity: 1
},
{
    id: 1110004,
        name: "prabhudarsan dhup",
        price: "",
        originalPrice: "",
        delivery_time: "20 min",
        amount: "",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "incense (dhup)",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},

//-------------Scurb---------------------
{
    id: 1111001,
        name: "shine no -1 scurb",
        price: 15,
        originalPrice: 15,
        delivery_time: "20 min",
        amount: "size= 7.5cm * 10cm",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "scurb",
        image: "",
        little_details: "3x more better regular green scurb pad",
        details: "",
        quantity: 1
},
{
    id: 1111002,
        name: "unique scurb",
        price: 15,
        originalPrice: 15,
        delivery_time: "20 min",
        amount: "size= 9.5cm * 10cm",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "scurb",
        image: "product images/daily products/unique scurb.JPG",
        little_details: "5x more better regular scurb pad",
        details: "Trusted by many peoples",
        quantity: 1
},


//------------------Masala----------------

{
    id: 1112001,
        name: "maggi masala",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "6g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/maggi masala.JPG",
        little_details: "magic with iron & vitamin b9",
        details: "1 serve = 2g, Pack contains 3 serves | How to use? Cook any dish as you normally do & Sprinkle a sachet 2-3 minutes before taking it off the flame.",
        quantity: 1
},
{
    id: 1112002,
        name: "meat masala sunrise",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "7g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/meat masala.JPG",
        little_details: "make cooking tasty",
        details: sunrisemasaladetail,
        quantity: 1
},

{
    id: 1112003,
        name: "cumin jeera powder sunrise",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "5g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/cumin jeera powder.JPG",
        little_details: "Cumin powder standard grade",
        details: sunrisemasaladetail,
        quantity: 1
},
{
    id: 1112004,
        name: "chow mix masala sunrise",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "7g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/chow mix.JPG",
        little_details: "",
        details: sunrisemasaladetail,
        quantity: 1
},
{
    id: 1112005,
        name: "kashmiri mirch powder sunrise",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "7g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/kashmiri mirch.JPG",
        little_details: "",
        details: sunrisemasaladetail,
        quantity: 1
},
{
    id: 1112006,
        name: "coriander dhania power sunrise",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "10g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/dhania powder.JPG",
        little_details: "",
        details: sunrisemasaladetail,
        quantity: 1
},

{
    id: 1112007,
        name: "lal mirch power sunrise",
        price: 5,
        originalPrice: 5,
        delivery_time: "20 min",
        message: "",
        amount: "7g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/lal mirch.JPG",
        little_details: "red chili",
        details: sunrisemasaladetail,
        quantity: 1
},
{
    id: 11120018,
        name: "kali mirch sunrise",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "6g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "masala",
        image: "product images/daily products/kali mirch.JPG",
        little_details: "black pepper",
        details: sunrisemasaladetail,
        quantity: 1
},
//---------Coffee------
{
    id: 1113001,
        name: "nescafe classic coffee",
        price: 30,
        originalPrice: 30,
        delivery_time: "20 min",
        message: "",
        amount: "0.9g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "coffee",
        image: "product images/daily products/nescafe coffee.JPG",
        little_details: "for a short cup",
        details: "Preparation: 1. Add 1 sachet NESCAFE 2. Add 90 ml of hot milk/water (Not boiling) 3.Add Sugar to taste | Ingredients: Coffee beans | 100% Pure coffee | Soluble coffe powder",
        quantity: 1
},



//---------salt------
{
    id: 1114001,
        name: "Tata salt ",
        price: 15,
        originalPrice: 15,
        delivery_time: "20 min",
        message: "",
        amount: "500g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "dailyProduct",
        sub_category: "coffee",
        image: "product images/daily products/tata salt.jpg",
        little_details: "iodine guarantee",
        details: "Over 40 years of trust | Vacuum Evaporated Edible Common Salt | Helps mental Development | Iodine is required for normal growth, Thyroid and brain function. It is generally accepted That Iodine helps in mental development of children.",
        quantity: 1
},






// ---------Other products-----------------

{
    id: 131001,
        name: "amulspray",
        price: 48,
        originalPrice: 48,
        delivery_time: "20 min",
        message: "",
        amount: "100g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "other",
        sub_category: "milk powder",
        image: "product images/other/milk powder amul 100.JPG",
        little_details: "Infant milk food | Infant milk substitute",
        details: " The prepared feed should be used within Half an hour. Otherwise microbial deterioration of the product may set in. Make a fresh preparation for every feed. Discard leftover feed. | Amulspary comes from the house of Amul: The Taste of India ",
        quantity: 1
},
{
    id: 131002,
        name: "amulspray",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "20g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "other",
        sub_category: "milk powder",
        image: "product images/other/milk powder amul 20.JPG",
        little_details: "Infant milk food | Infant milk substitute",
        details: " The prepared feed should be used within Half an hour. Otherwise microbial deterioration of the product may set in. Make a fresh preparation for every feed. Discard leftover feed. | Amulspary comes from the house of Amul: The Taste of India ",
        quantity: 1
},

{
    id: 131003,
        name: "godrej expert natural rich creme black 1.00",
        price: 15,
        originalPrice: 15,
        delivery_time: "20 min",
        message: "",
        amount: "12g + 12ml",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "other",
        sub_category: "hair colour",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},
{
    id: 131004,
        name: "garnier black naturals deep black 1.0",
        price: 10,
        originalPrice: 10,
        delivery_time: "20 min",
        message: "",
        amount: "20g",
        thumbnail1: "",
        thumbnail2: "",
        thumbnail3: "",
        category: "other",
        sub_category: "hair colour",
        image: "",
        little_details: "",
        details: "",
        quantity: 1
},











    
    

    // 👉 Add more products as needed
];
